# Generated by Django 3.2.5 on 2021-07-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_vinyl_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.record'),
            preserve_default=False,
        ),
    ]
