# Generated by Django 3.2.5 on 2021-07-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210716_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='record',
        ),
    ]
